export const CONTINENT_MAP = [
  {
    continent: 'Oceania',
    countries: [
      'American Samoa',
      'Australia',
      'Cook Islands',
      'Federated States of Micronesia',
      'Fiji',
      'French Polynesia',
      'Guam',
      'Hawaii',
      'Kiribati',
      'Marshall Islands',
      'Nauru',
      'New Caledonia',
      'New Zealand',
      'Niue',
      'Norfolk Island',
      'Northern Mariana Islands',
      'Palau',
      'Papua New Guinea',
      'Pitcairn Islands',
      'Samoa',
      'Solomon Islands',
      'Timor-Leste',
      'Tokelau',
      'Tonga',
      'Tuvalu',
      'Vanuatu',
      'Wallis and Futuna',
      'Western New Guinea',
    ],
  },
  {
    continent: 'Europe',
    countries: [
      'Albania',
      'Andorra',
      'Austria',
      'Belarus',
      'Belgium',
      'Bosnia and Herzegovina',
      'Bulgaria',
      'Channel Islands',
      'Croatia',
      'Czech Republic',
      'Denmark',
      'Estonia',
      'Faeroe Islands',
      'Finland',
      'France',
      'Germany',
      'Gibraltar',
      'Greece',
      'Holy See',
      'Hungary',
      'Iceland',
      'Ireland',
      'Isle of Man',
      'Italy',
      'Latvia',
      'Liechtenstein',
      'Lithuania',
      'Luxembourg',
      'Malta',
      'Moldova',
      'Monaco',
      'Montenegro',
      'Netherlands',
      'North Macedonia',
      'Norway',
      'Poland',
      'Portugal',
      'Romania',
      'Russia',
      'San Marino',
      'Serbia',
      'Slovakia',
      'Slovenia',
      'Spain',
      'Sweden',
      'Switzerland',
      'Ukraine',
      'United Kingdom',
      'Czechia',
    ],
  },
  {
    continent: 'Asia',
    countries: [
      'Bahrain',
      'China',
      'East Timor',
      'India',
      'Indonesia',
      'Iran',
      'Iraq',
      'Israel',
      'Japan',
      'Jordan',
      'Kazakhstan',
      'Myanmar',
      'North Korea',
      'South Korea',
      'Kuwait',
      'Kyrgyzstan',
      'Laos',
      'Malaysia',
      'Oman',
      'Pakistan',
      'Qatar',
      'Russian Federation',
      'Saudi Arabia',
      'Singapore',
      'Taiwan',
      'Thailand',
      'Turkey',
      'Turkmenistan',
      'United Arab Emirates',
      'Uzbekistan',
      'Vietnam',
      'Yemen',
      'Armenia',
      'Hong Kong',
    ],
  },
  {
    continent: 'Africa',
    countries: [
      'Algeria',
      'Angola',
      'Benin',
      'Botswana',
      'Burkina Faso',
      'Burundi',
      'Cabo Verde',
      'Cameroon',
      'Central African Republic',
      'Chad',
      'Comoros',
      'Congo',
      "Côte d'Ivoire",
      'Djibouti',
      'DR Congo',
      'Egypt',
      'Equatorial Guinea',
      'Eritrea',
      'Eswatini',
      'Ethiopia',
      'Gabon',
      'Gambia',
      'Ghana',
      'Guinea',
      'Guinea-Bissau',
      'Kenya',
      'Lesotho',
      'Liberia',
      'Libya',
      'Madagascar',
      'Malawi',
      'Mali',
      'Mauritania',
      'Mauritius',
      'Mayotte',
      'Morocco',
      'Mozambique',
      'Namibia',
      'Niger',
      'Nigeria',
      'Réunion',
      'Rwanda',
      'Saint Helena',
      'Sao Tome & Principe',
      'Senegal',
      'Seychelles',
      'Sierra Leone',
      'Somalia',
      'South Africa',
      'South Sudan',
      'Sudan',
      'Tanzania',
      'Togo',
      'Tunisia',
      'Uganda',
      'Western Sahara',
      'Zambia',
      'Zimbabwe',
    ],
  },
  {
    continent: 'North America',
    countries: [
      'Antigua and Barbuda',
      'Barbados',
      'Belize',
      'Canada',
      'Costa Rica',
      'Cuba',
      'Dominica',
      'Dominican Republic',
      'El Salvador',
      'Grenada',
      'Guatemala',
      'Haiti',
      'Honduras',
      'Jamaica',
      'Mexico',
      'Nicaragua',
      'Panama',
      'Saint Kitts and Nevis',
      'Saint Lucia',
      'Saint Vincent and the Grenadines',
      'The Bahamas',
      'Trinidad and Tobago',
      'United States',
      'Puerto Rico',
    ],
  },
  {
    continent: 'South America',
    countries: [
      'Argentina',
      'Bolivia',
      'Brazil',
      'Chile',
      'Colombia',
      'Ecuador',
      'French Guiana',
      'Guyana',
      'Paraguay',
      'Peru',
      'Suriname',
      'Uruguay',
      'Venezuela',
    ],
  },
];
